### ISSUE TITLE
File not parsed on open file dialog

### ISSUE THREAD

**Issue by eekrain** [Jcanotorr06/solid-dzone#2]
File that is imported using open file dialog did not get parsed. I tried cloning this repo and running dev, then console logging on before and after transformFiles helper returning empty array. It was because clearFiles() on handleFiles() getting called too early that it clears the file that was gonna be passed on to transformFiles()

**Comment by trucondev** [comment]
Hi! I have the same issue. It is merged, but not yet published as a release.
Can you create a new release with this fix?
Or is a larger release in the works?
Thank you!
